### ISSUE TITLE
genymotion is no longer available in a free pricing level

### ISSUE THREAD

**Issue by siruguri** [exponentjs/exponent-docs#14]
It looks like the Basic option was recently removed. This should be corrected in the docs. I can still see it in Google search results:

![screen shot 2016-10-26 at 4 48 38 pm](https://cloud.githubusercontent.com/assets/40653/19749216/136ba5ac-9b9c-11e6-938c-b4bbfd62bba9.png)

but clicking through, you can see it's been removed:

![screen shot 2016-10-26 at 4 49 03 pm](https://cloud.githubusercontent.com/assets/40653/19749221/2abc48ce-9b9c-11e6-8b5c-e9750ab77d52.png)

**Comment by siruguri** [comment]
Ah, the changes are in Github but only in the `unversioned` folder... not sure if you're about to deploy them to previous versions, so I'll leave this open for now

**Comment by brentvatne** [comment]
Heya @siruguri - thanks for pointing this out -- we updated sdk10 docs as well: https://docs.getexponent.com/versions/v10.0.0/introduction/installation.html#android-emulator

We didn't backport to older versions as hopefully people will not be installing from scratch for older versions ;> each version is much better than the last.

**Comment by iroshanAV** [comment]
Is it really gennymotion has free version?

**Comment by brentvatne** [comment]
@iroshanAV - yes there is a link in the docs that I link to above

<img width="887" alt="screen shot 2016-12-05 at 11 43 23 am" src="https://cloud.githubusercontent.com/assets/90494/20899641/0d29409c-bae0-11e6-9b82-55809ef6310b.png">

**Comment by hkrish0** [comment]
https://www.genymotion.com/fun-zone/
You can find the basic version in above url

**Comment by cjdcordeiro** [comment]
isn't there a way of making the Android simulator work without genymotion? Just by having Android Studio SDK installed...shouldn't that be enough?

**Comment by hkrish0** [comment]
@cjdcordeiro By default there is simulator with the SDK.

**Comment by cjdcordeiro** [comment]
@hkrish0 I already have it installed, but on expo I'm still getting: 
```
Couldn't start project on Android: Error running adb: No Android device found. Please connect a device and follow the instructions here to enable USB debugging:
https://developer.android.com/studio/run/device.html#developer-device-options. If you are using Genymotion go to Settings -> ADB, select "Use custom Android SDK tools", and point it at your Android SDK directory.```

**Comment by hkrish0** [comment]
1.Did you create emulator ?You have to create an emulator first.Check this link
https://www.embarcadero.com/starthere/xe5/mobdevsetup/android/en/creating_an_android_emulator.html
2.OR If you have an android phone use that for running your project

**Comment by hkrish0** [comment]
@cjdcordeiro Refer this link also
https://stackoverflow.com/questions/16596877/android-studio-doesnt-see-device/16598454

**Comment by cjdcordeiro** [comment]
@hkrish0 yes I do have the emulator and I can run it from within Android Studio. the problem seems to be that expo cannot find it

**Comment by brentvatne** [comment]
@cjdcordeiro - did you try following these steps? https://docs.expo.io/versions/v18.0.0/guides/genymotion.html

**Comment by cjdcordeiro** [comment]
@brentvatne well that still requires genymotion. I'd like to avoid using it completely cause of its free version restrictions

**Comment by brentvatne** [comment]
sorry we don't support the stock android emulator

**Comment by pedrosax** [comment]
@brentvatne - why doesn't Expo support the stock Android Emulator?

**Comment by brentvatne** [comment]
we are a small team, we don't use the stock android emulator because it is very bad compared to genymotion, it requires a significantly higher qa load to support it

**Comment by loloof64** [comment]
Hi, maybe that's the wrong place for asking that, but my Genymotion free license is about to expire in 3 days and I haven't found on their website how to renew it. So I may not be able to test my Expo apps on simulator starting from the next days.

Is there someone in the same case than mine ?

**Comment by BradRyan** [comment]
Genymotion is actually fairly expensive (if you are doing anything but making a "just for fun app") and from what I've read online the Android Studios emulator has gotten much better in recent times.  Not sure if that helps support the case for supporting the Android Studio emulator.

I haven't personally used either of them yet, just going off a bit of research before deciding what to do.  Is it possible to run a 'Create React Native App' from Android Studios without ejecting?

**Comment by RoyiNamir** [comment]
@loloof64 myne also. No longer free version?

**Comment by diabolusss** [comment]
![geny_free](https://user-images.githubusercontent.com/8426197/34032914-cbbf02a4-e180-11e7-9109-55f4225af649.png)
Free license still exist, only on each emulator run you'll receive this annoying message. And each time you must approve license agreement. And you can't sign in with genymotion account as it will be handled as business account(haven't found how to change that).

**Comment by hklcf** [comment]
@diabolusss but when you download fun-zone version, it need you login first, but my account is free license account :(

**Comment by corysimmons** [comment]
Can confirm Expo now costs $126/yr for solo dev.

https://www.genymotion.com/blog/2-9-0-android-7-1-new-trial-system/

It's a 30 day trial then you go back to "Fun Zone" version which has 1 image, and that image is broken because of Image vs Genymotion version mismatches (I suppose one could find an old version of Genymotion somewhere and hope it doesn't auto-update).

"Updating" as it instructs just fails and invites you to register.

Please support 2-3 images via Android Studio so poor people like myself (and the other 99.999% of the world who can't afford $126 **per year** for a GUI on already free emulation).

If you need help with the configs, I can advise and even write a guide for Expo users, but I don't have time to dig into Expo's codebase to implement whatever connection Expo needs to make to Android Studio.

**Comment by jesseruder** [comment]
@corysimmons we recommend Genymotion because it generally works better than the Android Studio emulators. It should work fine on the Android Studio emulator. If you run into an problem with it you can create a new issue.

> I can advise and even write a guide for Expo users
That would be great! Please submit a PR here https://github.com/expo/expo-docs if you think something is confusing.

**Comment by rokit** [comment]
> It should work fine on the Android Studio emulator.

How do you connect Expo to the Android Studio emulator? I can't find anything about this in the docs.

**Comment by anonym24** [comment]
free version stopped working:

> Your license has expired. Please renew your license to keep using Genymotion. https://www.genymotion.com/renew-license

using this link you can only go to buy full version...
