### ISSUE TITLE
Add documentation for interop with Relay

### ISSUE THREAD

**Issue by travisbloom** [exponentjs/exponent-docs#5]
The .babelrc needs to be edited to the config below in order to properly configure with Relay: 

```
{
    "presets": [
        "react-native-stage-0/decorator-support",
        {"plugins": ["./pathToYourBabelRelayPlguin/babelRelayPlugin"]}
    ],
    "env": {
        "development": {
            "plugins": ["transform-react-jsx-source"]
        }
    }
}
```

**Comment by brentvatne** [comment]
thanks a lot @travisbloom! I'll find a place in the docs for this

**Comment by brentvatne** [comment]
done! https://github.com/exponentjs/exponent-docs/commit/b010b6b16db530edeb607004dbda32132ed2bcf3
