### ISSUE TITLE
Installation doc should mention watchman as a prerequisite

### ISSUE THREAD

**Issue by ilya** [exponentjs/exponent-docs#8]
If you don't have watchman installed, the initial experience is frustrating as you have to wait on a long timeout to find out that you're missing it.

https://docs.getexponent.com/versions/v10.0.0/introduction/installation.html

**Comment by brentvatne** [comment]
Thanks @ilya! Fixed in https://github.com/exponentjs/exponent-docs/commit/e4a04f28b5fc8a989e6a209cee13cd8a0fcb04ab
